using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace CRM.Domain.Entity
{
    public static class ModelBuilderExtension
    {
        public static void Seed(this ModelBuilder builder)
        {
            List<Country> countries = new List<Country>()
            {
                new Country { Code = "US", Name = "United States" },
                    new Country { Code = "CA", Name = "Canada" },
                    new Country {Code = "AF", Name = "Afghanistan" },
                    new Country { Code = "AL", Name = "Albania" },
                    new Country { Code = "DZ", Name = "Algeria" },
                    new Country { Code = "AS", Name = "American Samoa" },
                    new Country { Code = "AD", Name = "Andorra" },
                    new Country { Code = "AO", Name = "Angola" },
                    new Country { Code = "AI", Name = "Anguilla" },
                    new Country { Code = "AQ", Name = "Antarctica" },
                    new Country { Code = "AG", Name = "Antigua and/or Barbuda" },
                    new Country { Code = "AR", Name = "Argentina" },
                    new Country { Code = "AM", Name = "Armenia" },
                    new Country { Code = "AW", Name = "Aruba" },
                    new Country { Code = "AU", Name = "Australia" },
                    new Country { Code = "AT", Name = "Austria" },
                    new Country { Code = "AZ", Name = "Azerbaijan" },
                    new Country { Code = "BS", Name = "Bahamas" },
                    new Country { Code = "BH", Name = "Bahrain" },
                    new Country { Code = "BD", Name = "Bangladesh" },
                    new Country { Code = "BB", Name = "Barbados" },
                    new Country { Code = "BY", Name = "Belarus" },
                    new Country { Code = "BE", Name = "Belgium" },
                    new Country { Code = "BZ", Name = "Belize" },
                    new Country { Code = "BJ", Name = "Benin" },
                    new Country { Code = "BM", Name = "Bermuda" },
                    new Country { Code = "BT", Name = "Bhutan" },
                    new Country { Code = "BO", Name = "Bolivia" },
                    new Country { Code = "BA", Name = "Bosnia and Herzegovina" },
                    new Country { Code = "BW", Name = "Botswana" },
                    new Country { Code = "BV", Name = "Bouvet Island" },
                    new Country { Code = "BR", Name = "Brazil" },
                    new Country { Code = "IO", Name = "British lndian Ocean Territory" },
                    new Country { Code = "BN", Name = "Brunei Darussalam" },
                    new Country { Code = "BG", Name = "Bulgaria" },
                    new Country { Code = "BF", Name = "Burkina Faso" },
                    new Country { Code = "BI", Name = "Burundi" },
                    new Country { Code = "KH", Name = "Cambodia" },
                    new Country { Code = "CM", Name = "Cameroon" },
                    new Country { Code = "CV", Name = "Cape Verde" },
                    new Country { Code = "KY", Name = "Cayman Islands" },
                    new Country { Code = "CF", Name = "Central African Republic" },
                    new Country { Code = "TD", Name = "Chad" },
                    new Country { Code = "CL", Name = "Chile" },
                    new Country { Code = "CN", Name = "China" },
                    new Country { Code = "CX", Name = "Christmas Island" },
                    new Country { Code = "CC", Name = "Cocos (Keeling) Islands" },
                    new Country { Code = "CO", Name = "Colombia" },
                    new Country { Code = "KM", Name = "Comoros" },
                    new Country { Code = "CG", Name = "Congo" },
                    new Country { Code = "CK", Name = "Cook Islands" },
                    new Country { Code = "CR", Name = "Costa Rica" },
                    new Country { Code = "HR", Name = "Croatia (Hrvatska)" },
                    new Country { Code = "CU", Name = "Cuba" },
                    new Country { Code = "CY", Name = "Cyprus" },
                    new Country { Code = "CZ", Name = "Czech Republic" },
                    new Country { Code = "CD", Name = "Democratic Republic of Congo" },
                    new Country { Code = "DK", Name = "Denmark" },
                    new Country { Code = "DJ", Name = "Djibouti" },
                    new Country { Code = "DM", Name = "Dominica" },
                    new Country { Code = "DO", Name = "Dominican Republic" },
                    new Country { Code = "TP", Name = "East Timor" },
                    new Country { Code = "EC", Name = "Ecudaor" },
                    new Country { Code = "EG", Name = "Egypt" },
                    new Country { Code = "SV", Name = "El Salvador" },
                    new Country { Code = "GQ", Name = "Equatorial Guinea" },
                    new Country { Code = "ER", Name = "Eritrea" },
                    new Country { Code = "EE", Name = "Estonia" },
                    new Country { Code = "ET", Name = "Ethiopia" },
                    new Country { Code = "FK", Name = "Falkland Islands (Malvinas)" },
                    new Country { Code = "FO", Name = "Faroe Islands" },
                    new Country { Code = "FJ", Name = "Fiji" },
                    new Country { Code = "FI", Name = "Finland" },
                    new Country { Code = "FR", Name = "France" },
                    new Country { Code = "FX", Name = "France, Metropolitan" },
                    new Country { Code = "GF", Name = "French Guiana" },
                    new Country { Code = "PF", Name = "French Polynesia" },
                    new Country { Code = "TF", Name = "French Southern Territories" },
                    new Country { Code = "GA", Name = "Gabon" },
                    new Country { Code = "GM", Name = "Gambia" },
                    new Country { Code = "GE", Name = "Georgia" },
                    new Country { Code = "DE", Name = "Germany" },
                    new Country { Code = "GH", Name = "Ghana" },
                    new Country { Code = "GI", Name = "Gibraltar" },
                    new Country { Code = "GR", Name = "Greece" },
                    new Country { Code = "GL", Name = "Greenland" },
                    new Country { Code = "GD", Name = "Grenada" },
                    new Country { Code = "GP", Name = "Guadeloupe" },
                    new Country { Code = "GU", Name = "Guam" },
                    new Country { Code = "GT", Name = "Guatemala" },
                    new Country { Code = "GN", Name = "Guinea" },
                    new Country { Code = "GW", Name = "Guinea-Bissau" },
                    new Country { Code = "GY", Name = "Guyana" },
                    new Country { Code = "HT", Name = "Haiti" },
                    new Country { Code = "HM", Name = "Heard and Mc Donald Islands" },
                    new Country { Code = "HN", Name = "Honduras" },
                    new Country { Code = "HK", Name = "Hong Kong" },
                    new Country { Code = "HU", Name = "Hungary" },
                    new Country { Code = "IS", Name = "Iceland" },
                    new Country { Code = "IN", Name = "India" },
                    new Country { Code = "ID", Name = "Indonesia" },
                    new Country { Code = "IR", Name = "Iran {Islamic Republic of}" },
                    new Country { Code = "IQ", Name = "Iraq" },
                    new Country { Code = "IE", Name = "Ireland" },
                    new Country { Code = "IL", Name = "Israel" },
                    new Country { Code = "IT", Name = "Italy" },
                    new Country { Code = "CI", Name = "Ivory Coast" },
                    new Country { Code = "JM", Name = "Jamaica" },
                    new Country { Code = "JP", Name = "Japan" },
                    new Country { Code = "JO", Name = "Jordan" },
                    new Country { Code = "KZ", Name = "Kazakhstan" },
                    new Country { Code = "KE", Name = "Kenya" },
                    new Country { Code = "KI", Name = "Kiribati" },
                    new Country { Code = "KP", Name = "Korea, Democratic People's Republic of" },
                    new Country { Code = "KR", Name = "Korea, Republic of" },
                    new Country { Code = "KW", Name = "Kuwait" },
                    new Country { Code = "KG", Name = "Kyrgyzstan" },
                    new Country { Code = "LA", Name = "Lao People's Democratic Republic" },
                    new Country { Code = "LV", Name = "Latvia" },
                    new Country { Code = "LB", Name = "Lebanon" },
                    new Country { Code = "LS", Name = "Lesotho" },
                    new Country { Code = "LR", Name = "Liberia" },
                    new Country { Code = "LY", Name = "Libyan Arab Jamahiriya" },
                    new Country { Code = "LI", Name = "Liechtenstein" },
                    new Country { Code = "LT", Name = "Lithuania" },
                    new Country { Code = "LU", Name = "Luxembourg" },
                    new Country { Code = "MO", Name = "Macau" },
                    new Country { Code = "MK", Name = "Macedonia" },
                    new Country { Code = "MG", Name = "Madagascar" },
                    new Country { Code = "MW", Name = "Malawi" },
                    new Country { Code = "MY", Name = "Malaysia" },
                    new Country { Code = "MV", Name = "Maldives" },
                    new Country { Code = "ML", Name = "Mali" },
                    new Country { Code = "MT", Name = "Malta" },
                    new Country { Code = "MH", Name = "Marshall Islands" },
                    new Country { Code = "MQ", Name = "Martinique" },
                    new Country { Code = "MR", Name = "Mauritania" },
                    new Country { Code = "MU", Name = "Mauritius" },
                    new Country { Code = "TY", Name = "Mayotte" },
                    new Country { Code = "MX", Name = "Mexico" },
                    new Country { Code = "FM", Name = "Micronesia, Federated States of" },
                    new Country { Code = "MD", Name = "Moldova, Republic of" },
                    new Country { Code = "MC", Name = "Monaco" },
                    new Country { Code = "MN", Name = "Mongolia" },
                    new Country { Code = "MS", Name = "Montserrat" },
                    new Country { Code = "MA", Name = "Morocco" },
                    new Country { Code = "MZ", Name = "Mozambique" },
                    new Country { Code = "MM", Name = "Myanmar" },
                    new Country { Code = "NA", Name = "Namibia" },
                    new Country { Code = "NR", Name = "Nauru" },
                    new Country { Code = "NP", Name = "Nepal" },
                    new Country { Code = "NL", Name = "Netherlands" },
                    new Country { Code = "AN", Name = "Netherlands Antilles" },
                    new Country { Code = "NC", Name = "New Caledonia" },
                    new Country { Code = "NZ", Name = "New Zealand" },
                    new Country { Code = "NI", Name = "Nicaragua" },
                    new Country { Code = "NE", Name = "Niger" },
                    new Country { Code = "NG", Name = "Nigeria" },
                    new Country { Code = "NU", Name = "Niue" },
                    new Country { Code = "NF", Name = "Norfork Island" },
                    new Country { Code = "MP", Name = "Northern Mariana Islands" },
                    new Country { Code = "NO", Name = "Norway" },
                    new Country { Code = "OM", Name = "Oman" },
                    new Country { Code = "PK", Name = "Pakistan" },
                    new Country { Code = "PW", Name = "Palau" },
                    new Country { Code = "PA", Name = "Panama" },
                    new Country { Code = "PG", Name = "Papua New Guinea" },
                    new Country { Code = "PY", Name = "Paraguay" },
                    new Country { Code = "PE", Name = "Peru" },
                    new Country { Code = "PH", Name = "Philippines" },
                    new Country { Code = "PN", Name = "Pitcairn" },
                    new Country { Code = "PL", Name = "Poland" },
                    new Country { Code = "PT", Name = "Portugal" },
                    new Country { Code = "PR", Name = "Puerto Rico" },
                    new Country { Code = "QA", Name = "Qatar" },
                    new Country { Code = "SS", Name = "Republic of South Sudan" },
                    new Country { Code = "RE", Name = "Reunion" },
                    new Country { Code = "RO", Name = "Romania" },
                    new Country { Code = "RU", Name = "Russian Federation" },
                    new Country { Code = "RW", Name = "Rwanda" },
                    new Country { Code = "KN", Name = "Saint Kitts and Nevis" },
                    new Country { Code = "LC", Name = "Saint Lucia" },
                    new Country { Code = "VC", Name = "Saint Vincent and the Grenadines" },
                    new Country { Code = "WS", Name = "Samoa" },
                    new Country { Code = "SM", Name = "San Marino" },
                    new Country { Code = "ST", Name = "Sao Tome and Principe" },
                    new Country { Code = "SA", Name = "Saudi Arabia" },
                    new Country { Code = "SN", Name = "Senegal" },
                    new Country { Code = "RS", Name = "Serbia" },
                    new Country { Code = "SC", Name = "Seychelles" },
                    new Country { Code = "SL", Name = "Sierra Leone" },
                    new Country { Code = "SG", Name = "Singapore" },
                    new Country { Code = "SK", Name = "Slovakia" },
                    new Country { Code = "SI", Name = "Slovenia" },
                    new Country { Code = "SB", Name = "Solomon Islands" },
                    new Country { Code = "SO", Name = "Somalia" },
                    new Country { Code = "ZA", Name = "South Africa" },
                    new Country { Code = "GS", Name = "South Georgia South Sandwich Islands" },
                    new Country { Code = "ES", Name = "Spain" },
                    new Country { Code = "LK", Name = "Sri Lanka" },
                    new Country { Code = "SH", Name = "St. Helena" },
                    new Country { Code = "PM", Name = "St. Pierre and Miquelon" },
                    new Country { Code = "SD", Name = "Sudan" },
                    new Country { Code = "SR", Name = "Suriname" },
                    new Country { Code = "SJ", Name = "Svalbarn and Jan Mayen Islands" },
                    new Country { Code = "SZ", Name = "Swaziland" },
                    new Country { Code = "SE", Name = "Sweden" },
                    new Country { Code = "CH", Name = "Switzerland" },
                    new Country { Code = "SY", Name = "Syrian Arab Republic" },
                    new Country { Code = "TW", Name = "Taiwan" },
                    new Country { Code = "TJ", Name = "Tajikistan" },
                    new Country { Code = "TZ", Name = "Tanzania, United Republic of" },
                    new Country { Code = "TH", Name = "Thailand" },
                    new Country { Code = "TG", Name = "Togo" },
                    new Country { Code = "TK", Name = "Tokelau" },
                    new Country { Code = "TO", Name = "Tonga" },
                    new Country { Code = "TT", Name = "Trinidad and Tobago" },
                    new Country { Code = "TN", Name = "Tunisia" },
                    new Country { Code = "TR", Name = "Turkey" },
                    new Country { Code = "TM", Name = "Turkmenistan" },
                    new Country { Code = "TC", Name = "Turks and Caicos Islands" },
                    new Country { Code = "TV", Name = "Tuvalu" },
                    new Country { Code = "UG", Name = "Uganda" },
                    new Country { Code = "UA", Name = "Ukraine" },
                    new Country { Code = "AE", Name = "United Arab Emirates" },
                    new Country { Code = "GB", Name = "United Kingdom" },
                    new Country { Code = "UM", Name = "United States minor outlying islands" },
                    new Country { Code = "UY", Name = "Uruguay" },
                    new Country { Code = "UZ", Name = "Uzbekistan" },
                    new Country { Code = "VU", Name = "Vanuatu" },
                    new Country { Code = "VA", Name = "Vatican City State" },
                    new Country { Code = "VE", Name = "Venezuela" },
                    new Country { Code = "VN", Name = "Vietnam" },
                    new Country { Code = "VG", Name = "Virgin Islands (British)" },
                    new Country { Code = "VI", Name = "Virgin Islands (U.S.)" },
                    new Country { Code = "WF", Name = "Wallis and Futuna Islands" },
                    new Country { Code = "EH", Name = "Western Sahara" },
                    new Country { Code = "YE", Name = "Yemen" },
                    new Country { Code = "YU", Name = "Yugoslavia" },
                    new Country { Code = "ZR", Name = "Zaire" },
                    new Country { Code = "ZM", Name = "Zambia" },
                    new Country { Code = "ZW", Name = "Zimbabwe" }
            };

            int i = 1;
            foreach (var country in countries)
            {
                country.Id = i;
                i += 1;
            }

            builder.Entity<Country>()
                .HasData(countries);
        }
    }
}